services:
  database:
    container_name: db-postgres
    image: postgres:16-alpine
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_DB: $PG_DBNAME
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    volumes:
      - ./postgres/create_schemas.sql:/docker-entrypoint-initdb.d/create_schemas.sql