spring:
  # Для добавления схемы для подключения к БД добавить в конец 'spring.r2dbc/liquibase.url':
  # '?currentSchema=${LEO_DB_SCHEMA_NAME:leo_bot_schema}'
  r2dbc:
    url: r2dbc:${LEO_DB_TYPE:postgresql}://${LEO_DB_HOST:localhost}:${LEO_DB_PORT:5123}/${LEO_DB_NAME:leo_db}
    username: ${LEO_DB_LOGIN:leo_login}
    password: ${LEO_DB_PASSWORD:leo_password}
  liquibase:
    url: jdbc:${LEO_DB_TYPE:postgresql}://${LEO_DB_HOST:localhost}:${LEO_DB_PORT:5123}/${LEO_DB_NAME:leo_db}
    user: ${LEO_DB_LOGIN:leo_login}
    password: ${LEO_DB_PASSWORD:leo_password}

logging:
  level:
    org:
      springframework:
        r2dbc: ${LEO_R2DBC_LOGGING_LEVEL:DEBUG}