spring:
  # Для добавления схемы для подключения к БД добавить в конец 'spring.r2dbc/liquibase.url':
  # '?currentSchema=${PT_DB_SCHEMA_NAME:protego_totalum}'
  r2dbc:
    url: r2dbc:${PT_DB_TYPE:postgresql}://${PT_DB_HOST:localhost}:${PT_DB_PORT:5123}/${PT_DB_NAME:protego_totalum}
    username: ${PT_DB_LOGIN:protego_totalum}
    password: ${PT_DB_PASSWORD:protego_totalum}
  liquibase:
    url: jdbc:${PT_DB_TYPE:postgresql}://${PT_DB_HOST:localhost}:${PT_DB_PORT:5123}/${PT_DB_NAME:protego_totalum}
    user: ${PT_DB_LOGIN:protego_totalum}
    password: ${PT_DB_PASSWORD:protego_totalum}
    liquibaseSchema: liquibase

logging:
  level:
    org:
      springframework:
        r2dbc: ${PT_R2DBC_LOGGING_LEVEL:DEBUG}